version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    image: dansatch/vidly-frontend:1
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    image: dansatch/vidly-backend:1
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017-27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
